services:
  # Single Linea Besu node with debugging enabled
  linea-besu-dev:
    image: consensys/linea-besu-package:latest
    container_name: linea-besu-dev
    command: >
      --profile=basic-mainnet
      --p2p-host=${PUBLIC_IP:-127.0.0.1}
      --rpc-http-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins="*"
      --rpc-ws-enabled=true
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --p2p-port=30303
      --max-peers=50
      --logging=DEBUG
      --metrics-enabled=true
      --metrics-host=0.0.0.0
      --metrics-port=9545
    environment:
      - JAVA_OPTS=-Xms2g -Xmx4g -XX:+UseG1GC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
      - "9545:9545"
      - "5005:5005"
    volumes:
      - besu_data_dev:/data
    restart: unless-stopped
    networks:
      - linea-dev-network

volumes:
  besu_data_dev:

networks:
  linea-dev-network:
    driver: bridge