global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-lb:9090']
    metrics_path: '/nginx_status'
    scrape_interval: 10s

  - job_name: 'besu-primary'
    static_configs:
      - targets: ['linea-besu-primary:9545']
    scrape_interval: 30s

  - job_name: 'besu-secondary'  
    static_configs:
      - targets: ['linea-besu-secondary:9545']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s